// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZTiYPnEqPD99H8PviUQgNXnZOG3Vonw',
    appId: '1:609152391063:web:de6d4208a169e79bf696d2',
    messagingSenderId: '609152391063',
    projectId: 'tourips-73681',
    authDomain: 'tourips-73681.firebaseapp.com',
    storageBucket: 'tourips-73681.appspot.com',
    measurementId: 'G-R2EQCF4FN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhf7f-9HwW7d_p3so3RUuJOdAzgKetmEo',
    appId: '1:609152391063:android:333500dd0a546ae5f696d2',
    messagingSenderId: '609152391063',
    projectId: 'tourips-73681',
    storageBucket: 'tourips-73681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtPmTKrocI1fy1-07RanXlraOFTmyT9M',
    appId: '1:609152391063:ios:3dce76c54b364a1bf696d2',
    messagingSenderId: '609152391063',
    projectId: 'tourips-73681',
    storageBucket: 'tourips-73681.appspot.com',
    iosBundleId: 'com.example.tourpis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtPmTKrocI1fy1-07RanXlraOFTmyT9M',
    appId: '1:609152391063:ios:bc0a3dffc3097c30f696d2',
    messagingSenderId: '609152391063',
    projectId: 'tourips-73681',
    storageBucket: 'tourips-73681.appspot.com',
    iosBundleId: 'com.example.tourpis.RunnerTests',
  );
}
